# Generated by Django 5.1.3 on 2024-11-21 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='byproduct',
            name='by_product_type',
        ),
        migrations.RemoveField(
            model_name='byproduct',
            name='potential_use',
        ),
        migrations.RemoveField(
            model_name='processing',
            name='processed_aluminum',
        ),
        migrations.RemoveField(
            model_name='processing',
            name='processing_date',
        ),
        migrations.AddField(
            model_name='byproduct',
            name='name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='byproduct',
            name='processing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='by_products', to='processing.processing'),
        ),
        migrations.AlterField(
            model_name='byproduct',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='processing',
            name='aluminum_output_estimate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='processing',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='quality',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(max_length=20),
        ),
    ]
